-- =============================================================================
-- Pingol Ramos Dental Clinic — Seed / Sample Data
-- Run AFTER schema.sql. Users are created separately by backend/setup.php
-- (bcrypt password hashes must be generated by PHP, never stored in SQL).
-- Dates are relative to CURDATE() so the dashboard always has fresh data.
-- =============================================================================

USE `pingol_ramos_dcms`;

-- ---- Clinic settings --------------------------------------------------------
INSERT INTO `settings` (`setting_key`,`setting_value`) VALUES
  ('clinic_name','Pingol Ramos Dental Clinic'),
  ('clinic_address','Poblacion, Bulacan, Philippines'),
  ('clinic_phone','0917-000-0000'),
  ('clinic_email','info@pingolramos.com'),
  ('operating_hours','Mon–Sat, 9:00 AM – 6:00 PM'),
  ('currency','PHP'),
  ('low_stock_default','10')
ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);

-- ---- Dentists ---------------------------------------------------------------
INSERT INTO `dentists` (`name`,`specialization`,`phone`,`email`) VALUES
  ('Dr. Maria Pingol','General Dentistry','0917-111-1111','m.pingol@pingolramos.com'),
  ('Dr. Jose Ramos','Orthodontics','0917-222-2222','j.ramos@pingolramos.com'),
  ('Dr. Ana Cruz','Endodontics','0917-333-3333','a.cruz@pingolramos.com'),
  ('Dr. Luis Santos','Oral Surgery','0917-444-4444','l.santos@pingolramos.com');

-- ---- Services / treatments offered -----------------------------------------
INSERT INTO `services` (`name`,`description`,`price`,`duration_minutes`) VALUES
  ('Dental Consultation','Initial check-up and assessment',500.00,30),
  ('Teeth Cleaning (Oral Prophylaxis)','Scaling and polishing',1200.00,45),
  ('Tooth Extraction','Simple extraction',1500.00,30),
  ('Dental Filling','Composite restoration',1800.00,45),
  ('Root Canal Treatment','Single-canal endodontic therapy',7000.00,90),
  ('Teeth Whitening','In-office whitening',8000.00,60),
  ('Braces Adjustment','Monthly orthodontic adjustment',1500.00,30),
  ('Dental Crown','Porcelain crown fitting',12000.00,60),
  ('Denture Fitting','Partial/complete denture',15000.00,60),
  ('Wisdom Tooth Surgery','Surgical extraction',6000.00,90);

-- ---- Suppliers --------------------------------------------------------------
INSERT INTO `suppliers` (`name`,`contact_person`,`phone`,`email`,`address`) VALUES
  ('DentSupply PH','Grace Lim','02-8888-1000','sales@dentsupply.ph','Quezon City'),
  ('MediDental Trading','Rico Tan','02-8888-2000','orders@medidental.ph','Manila'),
  ('OraCare Distributors','Bea Reyes','02-8888-3000','info@oracare.ph','Bulacan');

-- ---- Patients ---------------------------------------------------------------
INSERT INTO `patients`
  (`patient_code`,`first_name`,`last_name`,`birthdate`,`gender`,`address`,`contact_number`,`email`,
   `medical_history`,`allergies`,`existing_conditions`,`emergency_contact_name`,`emergency_contact_number`)
VALUES
  ('PT-0001','Juan','Dela Cruz','1990-04-12','male','Malolos, Bulacan','0918-100-0001','juan.delacruz@example.com','Hypertension, controlled','Penicillin','Hypertension','Maria Dela Cruz','0918-100-0002'),
  ('PT-0002','Andrea','Santos','1995-09-30','female','Guiguinto, Bulacan','0918-100-0003','andrea.santos@example.com','None','None','None','Pedro Santos','0918-100-0004'),
  ('PT-0003','Miguel','Reyes','1982-01-22','male','Plaridel, Bulacan','0918-100-0005','miguel.reyes@example.com','Diabetic Type 2','Latex','Diabetes','Rosa Reyes','0918-100-0006'),
  ('PT-0004','Sofia','Garcia','2001-06-18','female','Baliuag, Bulacan','0918-100-0007','sofia.garcia@example.com','None','Ibuprofen','None','Luis Garcia','0918-100-0008'),
  ('PT-0005','Carlo','Mendoza','1978-11-05','male','Pulilan, Bulacan','0918-100-0009','carlo.mendoza@example.com','Asthma','None','Asthma','Nena Mendoza','0918-100-0010'),
  ('PT-0006','Isabel','Torres','1988-03-14','female','Calumpit, Bulacan','0918-100-0011','isabel.torres@example.com','None','None','None','Mario Torres','0918-100-0012'),
  ('PT-0007','Rafael','Aquino','1993-07-27','male','Marilao, Bulacan','0918-100-0013','rafael.aquino@example.com','None','Aspirin','None','Liza Aquino','0918-100-0014'),
  ('PT-0008','Camille','Bautista','1999-12-02','female','Meycauayan, Bulacan','0918-100-0015','camille.bautista@example.com','None','None','None','Jomar Bautista','0918-100-0016');

-- ---- Appointments (relative dates) -----------------------------------------
-- Today
INSERT INTO `appointments`
  (`appointment_code`,`patient_id`,`dentist_id`,`service_id`,`appointment_date`,`start_time`,`end_time`,`status`,`notes`)
VALUES
  ('AP-0001',1,1,2,CURDATE(),'09:00:00','09:45:00','approved','Regular cleaning'),
  ('AP-0002',2,2,7,CURDATE(),'10:00:00','10:30:00','approved','Braces adjustment'),
  ('AP-0003',3,1,1,CURDATE(),'11:00:00','11:30:00','pending','Toothache complaint'),
  ('AP-0004',4,3,5,CURDATE(),'13:30:00','15:00:00','pending','Root canal continuation');
-- Tomorrow
INSERT INTO `appointments`
  (`appointment_code`,`patient_id`,`dentist_id`,`service_id`,`appointment_date`,`start_time`,`end_time`,`status`,`notes`)
VALUES
  ('AP-0005',5,4,10,DATE_ADD(CURDATE(), INTERVAL 1 DAY),'09:00:00','10:30:00','approved','Wisdom tooth surgery'),
  ('AP-0006',6,1,4,DATE_ADD(CURDATE(), INTERVAL 1 DAY),'11:00:00','11:45:00','pending','Filling');
-- Later this week
INSERT INTO `appointments`
  (`appointment_code`,`patient_id`,`dentist_id`,`service_id`,`appointment_date`,`start_time`,`end_time`,`status`,`notes`)
VALUES
  ('AP-0007',7,2,6,DATE_ADD(CURDATE(), INTERVAL 3 DAY),'14:00:00','15:00:00','pending','Whitening'),
  ('AP-0008',8,1,1,DATE_ADD(CURDATE(), INTERVAL 4 DAY),'10:30:00','11:00:00','pending','New patient consult');
-- Past (completed / cancelled)
INSERT INTO `appointments`
  (`appointment_code`,`patient_id`,`dentist_id`,`service_id`,`appointment_date`,`start_time`,`end_time`,`status`,`notes`)
VALUES
  ('AP-0009',1,1,1,DATE_SUB(CURDATE(), INTERVAL 20 DAY),'09:00:00','09:30:00','completed','Initial consult'),
  ('AP-0010',3,3,3,DATE_SUB(CURDATE(), INTERVAL 15 DAY),'10:00:00','10:30:00','completed','Extraction'),
  ('AP-0011',2,1,2,DATE_SUB(CURDATE(), INTERVAL 10 DAY),'11:00:00','11:45:00','completed','Cleaning'),
  ('AP-0012',5,4,3,DATE_SUB(CURDATE(), INTERVAL 5 DAY),'13:00:00','13:30:00','cancelled','Patient rescheduled');

-- ---- Treatments (dental records) -------------------------------------------
INSERT INTO `treatments`
  (`patient_id`,`appointment_id`,`dentist_id`,`treatment_name`,`tooth_number`,`diagnosis`,`procedure_notes`,`prescription`,`cost`,`treatment_date`)
VALUES
  (1,9,1,'Dental Consultation',NULL,'Mild gingivitis','Advised oral prophylaxis','Chlorhexidine mouth rinse',500.00,DATE_SUB(CURDATE(), INTERVAL 20 DAY)),
  (3,10,3,'Tooth Extraction','#36','Non-restorable molar','Simple extraction, no complications','Amoxicillin 500mg, Mefenamic 500mg',1500.00,DATE_SUB(CURDATE(), INTERVAL 15 DAY)),
  (2,11,1,'Teeth Cleaning','Full arch','Moderate calculus','Scaling and polishing completed',NULL,1200.00,DATE_SUB(CURDATE(), INTERVAL 10 DAY));

-- ---- Inventory --------------------------------------------------------------
INSERT INTO `inventory`
  (`product_name`,`category`,`quantity`,`unit`,`reorder_level`,`purchase_price`,`selling_price`,`supplier_id`,`expiration_date`)
VALUES
  ('Dental Anesthetic (Lidocaine 2%)','Anesthetics',40,'vials',15,45.00,80.00,1,DATE_ADD(CURDATE(), INTERVAL 8 MONTH)),
  ('Composite Resin Kit','Restorative',6,'kits',10,1200.00,1800.00,1,DATE_ADD(CURDATE(), INTERVAL 14 MONTH)),
  ('Disposable Gloves (Box)','Consumables',8,'boxes',20,180.00,250.00,2,DATE_ADD(CURDATE(), INTERVAL 24 MONTH)),
  ('Surgical Face Masks (Box)','Consumables',3,'boxes',15,120.00,180.00,2,DATE_ADD(CURDATE(), INTERVAL 20 MONTH)),
  ('Dental Cotton Rolls','Consumables',60,'packs',20,40.00,70.00,3,DATE_ADD(CURDATE(), INTERVAL 30 MONTH)),
  ('Fluoride Gel','Preventive',12,'tubes',8,220.00,350.00,1,DATE_ADD(CURDATE(), INTERVAL 2 MONTH)),
  ('Orthodontic Brackets (Set)','Orthodontic',5,'sets',6,2500.00,4000.00,3,DATE_ADD(CURDATE(), INTERVAL 36 MONTH)),
  ('Dental Impression Material','Restorative',0,'kits',5,900.00,1400.00,2,DATE_ADD(CURDATE(), INTERVAL 10 MONTH)),
  ('Whitening Gel Syringes','Cosmetic',4,'boxes',6,1500.00,2500.00,1,DATE_SUB(CURDATE(), INTERVAL 1 MONTH)),
  ('Sterilization Pouches','Consumables',50,'packs',15,150.00,220.00,3,DATE_ADD(CURDATE(), INTERVAL 18 MONTH));

-- ---- Expenses ---------------------------------------------------------------
INSERT INTO `expenses` (`category`,`title`,`amount`,`expense_date`,`notes`) VALUES
  ('rent','Clinic monthly rent',25000.00,DATE_FORMAT(CURDATE(),'%Y-%m-05'),'July rent'),
  ('utilities','Electricity bill',8500.00,DATE_FORMAT(CURDATE(),'%Y-%m-08'),'Meralco'),
  ('utilities','Water bill',1200.00,DATE_FORMAT(CURDATE(),'%Y-%m-08'),NULL),
  ('supplies','Restock consumables',6800.00,DATE_SUB(CURDATE(), INTERVAL 6 DAY),'Gloves + masks'),
  ('salaries','Staff salaries',60000.00,DATE_FORMAT(CURDATE(),'%Y-%m-15'),'2 dental assistants + receptionist'),
  ('maintenance','Dental chair servicing',3500.00,DATE_SUB(CURDATE(), INTERVAL 12 DAY),'Annual maintenance'),
  ('equipment','New autoclave sterilizer',45000.00,DATE_SUB(CURDATE(), INTERVAL 25 DAY),'Capital purchase');

-- ---- Payments (revenue) -----------------------------------------------------
INSERT INTO `payments` (`patient_id`,`appointment_id`,`amount`,`payment_method`,`payment_date`,`description`) VALUES
  (1,9,500.00,'cash',DATE_SUB(CURDATE(), INTERVAL 20 DAY),'Consultation'),
  (3,10,1500.00,'gcash',DATE_SUB(CURDATE(), INTERVAL 15 DAY),'Tooth extraction'),
  (2,11,1200.00,'cash',DATE_SUB(CURDATE(), INTERVAL 10 DAY),'Teeth cleaning'),
  (4,NULL,3500.00,'card',DATE_SUB(CURDATE(), INTERVAL 8 DAY),'Root canal downpayment'),
  (5,NULL,6000.00,'bank_transfer',DATE_SUB(CURDATE(), INTERVAL 4 DAY),'Wisdom tooth surgery deposit'),
  (6,NULL,1800.00,'cash',DATE_SUB(CURDATE(), INTERVAL 2 DAY),'Dental filling'),
  (7,NULL,8000.00,'gcash',DATE_SUB(CURDATE(), INTERVAL 1 DAY),'Teeth whitening');

-- ---- Sample notifications ---------------------------------------------------
INSERT INTO `notifications` (`user_id`,`type`,`title`,`message`,`link`) VALUES
  (NULL,'appointment','New appointment request','Miguel Reyes requested a consultation today','/appointments'),
  (NULL,'inventory','Low stock alert','Surgical Face Masks below reorder level','/inventory'),
  (NULL,'payment','Payment received','₱8,000 whitening payment recorded','/revenue');
